### ISSUE TITLE
Clean cache?

### ISSUE THREAD

**Issue by Menalix** [Rayquaza01/HistoryCleaner#31] opened 2024-02-01 16:56 UTC
I wondered if it could be possible to do the same with cache files? so if the website haven't had a visit for more than specificied duration it will clean up all cache files related to it?

**Comment by Rayquaza01** [comment] 2024-02-01 18:22
Duplicate of #13

The WebExtension API to clear the cache is [`browsingData`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData). With the `browsingData` APIs, you can only clear *recent* cache, cookies, history, etc.. There is no API to clear old cache like there is for history.

If you want to clear recent browsing data, there is a menu for this built into the browser. See [Delete browsing, search and download history on Mozilla Support](https://support.mozilla.org/en-US/kb/delete-browsing-search-download-history-firefox#w_how-do-i-clear-my-history)

[Cookie AutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/) might accomplish something similar to what you want. Along with cookies, you can configure CAD to clear other browsing data automatically. CAD uses a whitelist instead of expiration, so *all* cookies and other browsing data will be deleted for non-whitelisted sites.

I know you didn't mention cookies specifically, but for completeness, there is also an extension called [Fresh Cookies](https://addons.mozilla.org/en-US/firefox/addon/fresh-cookies/) which clears old cookies after an expiration.

Hope this helps!

**Closed by Rayquaza01** 2024-02-01 18:22 UTC
