### ISSUE TITLE
Add-on doesn't delete history

### ISSUE THREAD

**Issue by nadesco** [Rayquaza01/HistoryCleaner#5] opened 2019-09-20 06:42 UTC
Hi, 
I installed History Cleaner a day ago but it doesn't work.
My sidebar shows History going back to "Older than 6 months" so I set "Number of days to keep history" to 90 days in Preferences, but the folders and files for history older than this are still there. I've left Firefox idle for well over the 1 minute mark a number of times and also restarted my browser/machine. 
I might've missed something although the only thing I see in Prefs is a box to increase/decrease the number of days -- Thanks

OS X 10.14.6 Mojave
Firefox 70.0b7
Addon ver. 1.2.3

**Comment by Rayquaza01** [comment] 2019-09-26 13:42
Hello,
I'm not sure why it's not working for you. Could you open the browser console (Hamburger menu > Web Developer > Browser Console) and see if it logs any errors when it should be deleting history.

**Comment by nadesco** [comment] 2019-09-26 14:48
Not really sure what to look for but I checked the browser console and a search didn't bring up anything related to history. Although that might be because I created a new places.sqlite file earlier today and so all history was deleted (along with older error messages?). I decided to clean it up because it occurred to me that the previous file (about 32MB) was possibly corrupted. Anyway, I've now set HC preferences to 1 day so will see how it goes.

**Comment by nadesco** [comment] 2019-09-26 15:34
Thanks for your message. Not really sure what to look for but I checked the browser console and a search didn't bring up anything related to history. Although that might be because I created a new places.sqlite file earlier today and so all history was deleted (along with older error messages?). I decided to clean it up because it occurred to me that the previous file (about 32MB) was possibly corrupted. Anyway, I've now set HC preferences to 1 day so will see how it goes.

**Comment by anonymous-user** [comment] 2019-10-13 00:45
I am having the same issue with this addon. I am running Firefox Nightly and changed the setting for History Cleaner to just keep 60 days of history yet even after idling for a minute, my full history remains and I have items from way more than 60 days ago.

**Comment by Rayquaza01** [comment] 2019-10-14 22:37
@anonymous-user I tested it with Nightly and I still wasn't able to reproduce the issue. If you haven't checked the logs, could you? They are in a different place on Nightly. Go to `about:debugging#/runtime/this-firefox` and find History Cleaner on the list. Select `Inspect` and go to the `Console` tab in the new tab that opens.

If you don't see anything odd, could you try running these commands in the console just to see if they're working? The first one will log a message to the console when the browser idles, and the second one should delete everything up to the last 60 days.

`browser.idle.onStateChanged.addListener(console.log);`

`browser.history.deleteRange({ startTime: 0, endTime: Date.now() - (60 * 86400000)});`

**Comment by anonymous-user** [comment] 2019-10-15 01:47
Here is the output of the console:

* Content Security Policy: Couldn’t parse invalid host 'wasm-eval'
* The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. background.html
* Unknown localization message weh_prefs_label_downloadcompletedelay main.js:1
* Unknown localization message weh_prefs_description_downloadcompletedelay main.js:1
* Unknown localization message weh_prefs_label_tbvwsgrabdelay main.js:1
* Unknown localization message weh_prefs_description_tbvwsgrabdelay main.js:1
* Unknown localization message weh_prefs_label_forcedcoappversion main.js:1
* Unknown localization message weh_prefs_description_forcedcoappversion main.js:1
* The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. bg.html
* Loading failed for the <script> with source “http://www.googleadservices.com/pagead/conversion_async.js”. bg.html:1:1
* Loading failed for the <script> with source “http://connect.facebook.net/en_US/fbevents.js”. bg.html:1:1
* Loading failed for the <script> with source “http://www.google-analytics.com/analytics.js”. bg.html:1:1
* Content Security Policy: The page’s settings blocked the loading of a resource at http://www.googleadservices.com/pagead/conversion_async.js (“script-src”). 2 analytics-core.js:16704:37
* Content Security Policy: The page’s settings blocked the loading of a resource at http://connect.facebook.net/en_US/fbevents.js (“script-src”). 2 analytics-core.js:16704:37
* Content Security Policy: The page’s settings blocked the loading of a resource at http://www.google-analytics.com/analytics.js (“script-src”). 2 analytics-core.js:16704:37
* uncaught exception: 2
* Attempt to postMessage on disconnected port app.js:1612

-------------------------------------------------------------------------------------------------

So I ran the first command it returned "undefined". I ran the second item and I got:

18:45:47.411
Promise { "pending" }
​
<state>: "pending"
​
<prototype>: PromiseProto { … }

and 

18:45:47.658 Error: An unexpected error occurred undefined

**Comment by streetwolf** [comment] 2019-10-16 13:17
I'm having a similar problem.  Can the problem be caused by syncing with other devices, like my smart phones, where I keep history for a longer period of time?

**Comment by Rayquaza01** [comment] 2019-10-16 17:17
@anonymous-user Those messages in the console are likely from other extensions and webpages you have open. The first command returning undefined is good, but they second one threw an error? I assume that it didn't actually delete the history after running it?

**Comment by Rayquaza01** [comment] 2019-10-16 17:19
@streetwolf Syncing should not affect it. This extension doesn't sync the setting between devices. But if you sync history between devices, then deleting history on one device should delete it on the others.

**Comment by streetwolf** [comment] 2019-10-16 17:37
This morning when I used another program to look at my Mozilla history file it had entries from Oct. 11 until today.  I have the number of days in HC set to 1 which leaves about 2 days worth of history.  HC did this one time before which I thought was a syncing problem so I turned off syncing.  I then started getting 2 days worth until today.

I believe the older history is coming back from somewhere.  Furthermore when I got into Firefox and sat idle for a few minutes the older entries were not deleted.  Perhaps there is something else going on.  I am on Nightly so maybe Mozilla made some changes to the History mechanism.

___________
Gary Shapiro

________________________________

**Comment by anonymous-user** [comment] 2019-10-17 01:13
@Rayquaza01 correct. My history remains unchanged and I still have the old entries.

**Comment by nadesco** [comment] 2019-10-17 02:04
It now works for me, at least for short term deletions. The solution was to trash my places.sqlite file and start afresh.
I did this 20 days ago (see post above) and set history to 90 days. I decided to test it again and just changed it to 15 days. After the minute wait all the entries for Sept had disappeared.
My guess is that you either have a corrupted places.sqlite file or, for some reason, the add-on doesn’t work properly with larger files containing entries over many months.

**Comment by Tibladar** [comment] 2019-12-06 16:30
I got the same problem on FF 70.0.1 (release, no kind of syncing) Ubuntu 18.04.3 with addon version 1.2.3.

The Eventlistener shows it ran but the deleteRange command you provided in https://github.com/Rayquaza01/HistoryCleaner/issues/5#issuecomment-541961271 prints
![](https://user-images.githubusercontent.com/52620063/70338714-540a6980-1845-11ea-8c95-2135acf5545f.png)
or sometimes only
`Promise { <state>: "pending" }`
and in both cases the history doesn't change.

**Comment by DarthBrandon** [comment] 2019-12-09 23:16
I'm having the same issue.  Firefox 70.0.1 64-bit on openSUSE Tumbleweed Linux.

I followed the instructions and went to the Debugging page and opened the add-on console.  I entered the commands, and got the same result as Tibladar.  **An unexpected error occurred** when it tried to delete my history.

When I entered the command with a number of days larger than what my current history contains, it throws no errors, but when I put in a number less than my total history, where it actually has to delete some entries, it throws the error.

I had been using a different add-on to keep pruning my history, but that started failing a month or two ago.  So it doesn't seem to be an issue exclusive to this add-on.

**Comment by streetwolf** [comment] 2019-12-27 00:07
I no longer have this issue using Fx Nightly under Windows 10.  The 'problem' might have been the fact that it takes about a minute of idle time in order for the deletes to occur.  Perhaps I was not allowing enough idle time.  This being said I would like to see an option to delete history when Fx starts up.

**Comment by DarthBrandon** [comment] 2019-12-27 02:43
I don't think the issue is idle time, at least not on my end.  I can leave Firefox open for hours at a time while I'm AFK, and the add-on still won't delete any history.  Though, I guess it would depend on if other add-ons can affect the idle status.  That doesn't explain why I get error messages when trying to force the add-on to run, however.

**Comment by DarthBrandon** [comment] 2020-01-01 07:40
Ah, never mind that last post, I guess.  openSUSE Tumbleweed put Firefox 71 on their repos, and this issue seems to be fixed.  Still may not have been idle time, but it seems like it might have been a Firefox bug that got fixed rather than a bug with the add-on.  Here's hoping it stays fixed.

**Comment by streetwolf** [comment] 2020-01-31 22:55
I'm still having this issue but it is intermittent.  I have the number of history days to keep set to 1. It doesn't make a difference what number I choose but 1 makes it easy to see if things aren't working right.  Up until around 1/29/2020 it was working fine.  Now I have history from 1/29 to 1/31.  History from this point on won't be deleted.  I had to clear my history to get things working again.  I'll try to keep an eye on things and make a note if anything unusual happens in Firefox that might be causing this.  Perhaps it's a crash or maybe even setting a preference.  I like to try out prefs that aren't enabled by default.  Some I imagine aren't even stable yet.  I'll report back if I can pin point something for you.

**Comment by streetwolf** [comment] 2020-02-03 19:53
Again it happened.  My history is not being deleted.  I am what one might call a PC enthusiast, that is I like to tinker with both hardware and especially settings in my BIOS.  One strange consequence of fiddling with my BIOS settings is that every once in a while after a reboot to Windows with some new BIOS setting Firefox starts up automatically.  As I was not even in Firefox when I shutdown to make BIOS changes I have no idea why it starts up.  It is always any empty tab.  It has nothing to do with session restore as I don't have that enabled and as I said I was not in Firefox at all.  I'm thinking this behavior might be the cause of my history problem.  Just a guess at this point but it's plausible.  History never gets deleted after it stops working unless I clear out the history file manually.

**Comment by streetwolf** [comment] 2020-02-08 14:05
As a test I disabled HC and installed the similar add-on History AutoDelete.  Things were going smoothly until I had an issue with Fx starting up in a somewhat dubious state.  None of my add-ons appeared to be working and no add-on icons.  Also there were problems getting to sites.  I got around all that and then discovered that my old history entries were not being deleted similar to HC.  It must be when Fx gets into some 'funky' situation that both add-ons do not delete history.  So if misery loves company here you have it :-(

**Comment by webcaptcha** [comment] 2020-02-21 08:40
Guys, I'm having the same issue. I'm using Linux and latest version of addon. I have settings to keep 170 days of the history, but still see items older than 6 month in the my history.

**Comment by sergeyklay** [comment] 2020-09-01 19:46
Does not work for me too.

After installing the extension, setting "Numbers of days to keep history" to **1 day** and restart the browser I still see all browser history here:

![image](https://user-images.githubusercontent.com/1256298/91898496-792ceb00-eca4-11ea-95be-2c2e2c0658e1.png)


Firefox version: 80.0 (64-bit).
Logs:
```
22:35:08.817 Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). background.js:3759:15
22:36:51.548 Uncaught (in promise) Error: Type error for parameter details (Error processing tabId: Integer -1 is too small (must be at least 0)) for browserAction.setIcon.
    setTabIconActive moz-extension://1fb92702-9302-4cd6-aebc-d3dd383a8c69/js/utils.js:51
utils.js:51:12
22:36:51.548 Uncaught (in promise) Error: Type error for parameter details (Error processing tabId: Integer -1 is too small (must be at least 0)) for browserAction.setBadgeText.
    safeSetBadgeText moz-extension://1fb92702-9302-4cd6-aebc-d3dd383a8c69/js/utils.js:57
utils.js:57:17
22:39:36.349
Unchecked lastError value: Error: Missing host permission for the tab background.js:2
22:39:36.357
Unchecked lastError value: Error: Missing host permission for the tab background.js:2
22:40:28.583
Error: Can't find profile directory. 2 XULStore.jsm:66:15
```

**Comment by webcaptcha** [comment] 2020-09-03 11:28
Looks like extension is working, but for unknown reasons it delete entries not immediately.

**Comment by Rayquaza01** [comment] 2020-11-25 14:58
Hello,
I made a new pre-release version https://github.com/Rayquaza01/HistoryCleaner/releases/tag/v1.2.4rc1.

It adds an option to show a notification when history is deleted, as well as a button to delete history from the options page, which will hopefully help with debugging this issue.

If you want to try the pre-release, install the file from the link above using `about:debugging`.
Then: Open `Hamburger Menu > Web Developer > Browser Console`. Press the trash can icon at the top left of the window to clear the logs. Then, let your browser idle for 60 seconds (or the user set idle length) or press the Manual Delete button. If anything new gets added to the console after history should have been deleted, post it here.

**Comment by Rayquaza01** [comment] 2024-06-21 00:17
Since there have been no new additions to this issue since I added notifications in 2020, I'm going to assume that whatever was causing this is now fixed.

If anyone is still having this problem, you may still comment here or open a new issue.

**Closed by Rayquaza01** 2024-06-21 00:17 UTC
Labels: needs-reproduction
