### ISSUE TITLE
Clean also the downloads history?

### ISSUE THREAD

**Issue by phaolo2** [Rayquaza01/HistoryCleaner#20] opened 2021-10-21 23:45 UTC
Could you please add an option to clean also the downloads history?
Firefox never does it, for some reason..

**Comment by herrbrixter** [comment] 2024-06-20 23:20
Don't make this a default. Unlike the history, the downloads are important to me and I have far less downloaded files than internet history. I don't want my downloads like important pictures or documents to be accidentally deleted by Firefox.

**Comment by herrbrixter** [comment] 2024-06-20 23:42
This is a duplicate of #2

**Closed** 2024-06-20 23:48 UTC
Labels: enhancement
