### ISSUE TITLE
Domain Exceptions

### ISSUE THREAD

**Issue by devycarol** [Rayquaza01/HistoryCleaner#25] opened 2022-04-30 23:23 UTC
I've always wanted a way to make history expire like this and I was elated when I found this add-on. However, a lot of people rely on browser history chiefly to recall the names of certain webpages such as YouTube videos which have been removed. I think it would be cool to be able to exempt certain websites from cleaning so that users can have a rolling browser history with the ability to still keep a long-term history for specific websites.

**Comment by Rayquaza01** [comment] 2024-06-21 00:31
Closing as duplicate of #12.

**Closed by Rayquaza01** 2024-06-21 00:31 UTC
